import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgDark,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBg,
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandIcon: {
    fontSize: 28,
    marginRight: 10,
  },
  brandTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  brandSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  healthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  dotOnline: {
    backgroundColor: colors.green,
  },
  dotOffline: {
    backgroundColor: colors.errorBorder,
  },
  healthText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  heroSection: {
    marginTop: 30,
    alignItems: 'center',
  },
  heroBadge: {
    color: colors.gold,
    backgroundColor: colors.goldBgLight,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 12,
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 10,
  },
  heroDescription: {
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: 'center',
    maxWidth: 500,
    lineHeight: 22,
    marginBottom: 24,
  },
  formCard: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: colors.cardBg,
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  formLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  input: {
    backgroundColor: colors.bgDark,
    borderColor: colors.cardBorderLight,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: 16,
  },
  genderRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  genderBtn: {
    flex: 1,
    paddingVertical: 10,
    backgroundColor: colors.bgDark,
    borderWidth: 1,
    borderColor: colors.cardBorderLight,
    borderRadius: 10,
    alignItems: 'center',
  },
  genderBtnActive: {
    backgroundColor: colors.redBgLight,
    borderColor: colors.red,
  },
  genderText: {
    color: colors.textSecondary,
    fontWeight: '600',
  },
  genderTextActive: {
    color: colors.textPrimary,
  },
  calculateBtn: {
    backgroundColor: colors.red,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  calculateBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  resultsContainer: {
    marginTop: 40,
    width: '100%',
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  resultGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  resultCard: {
    flex: 1,
    minWidth: 240,
    backgroundColor: colors.cardBg,
    padding: 20,
    borderRadius: 14,
    borderWidth: 1,
  },
  goldBorder: {
    borderColor: colors.gold,
  },
  redBorder: {
    borderColor: colors.red,
  },
  cardTag: {
    fontSize: 11,
    fontWeight: 'bold',
    color: colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 6,
  },
  dayMasterTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.gold,
  },
  dayMasterChinese: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginVertical: 2,
  },
  kuaNumber: {
    fontSize: 32,
    fontWeight: '900',
    color: colors.red,
  },
  cardDesc: {
    color: colors.textMuted,
    fontSize: 13,
    marginTop: 6,
  },
  directionPill: {
    backgroundColor: colors.greenBgLight,
    padding: 8,
    borderRadius: 8,
    marginTop: 10,
  },
  directionText: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '600',
  },
  teaserCard: {
    backgroundColor: colors.teaserBg,
    borderColor: colors.cardBorderLight,
    borderWidth: 1,
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
  },
  teaserBadge: {
    color: colors.teaserBadge,
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  teaserText: {
    color: colors.teaserText,
    fontSize: 14,
    lineHeight: 20,
  },
  almanacSection: {
    marginTop: 40,
  },
  almanacGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  almanacBoxGood: {
    flex: 1,
    minWidth: 240,
    backgroundColor: colors.greenBoxBg,
    borderColor: colors.greenBoxBorder,
    borderWidth: 1,
    padding: 16,
    borderRadius: 12,
  },
  almanacLabelGood: {
    color: colors.green,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  almanacBoxAvoid: {
    flex: 1,
    minWidth: 240,
    backgroundColor: colors.dangerBoxBg,
    borderColor: colors.dangerBoxBorder,
    borderWidth: 1,
    padding: 16,
    borderRadius: 12,
  },
  almanacLabelAvoid: {
    color: colors.danger,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  almanacItem: {
    color: colors.textMuted,
    fontSize: 13,
    marginVertical: 2,
  },
  ctaBanner: {
    marginTop: 40,
    backgroundColor: colors.ctaBg,
    ...({ backgroundImage: 'linear-gradient(135deg, #1E1B4B 0%, #31103F 100%)' } as any),
    padding: 28,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.ctaBorder,
    alignItems: 'center',
  },
  ctaTag: {
    color: colors.ctaTag,
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 1,
    marginBottom: 8,
  },
  ctaTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  ctaSubtitle: {
    color: colors.ctaSubtitle,
    fontSize: 14,
    textAlign: 'center',
    maxWidth: 500,
    lineHeight: 20,
    marginBottom: 20,
  },
  ctaBtn: {
    backgroundColor: colors.ctaBtn,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
  },
  ctaBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  footer: {
    marginTop: 50,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.cardBg,
    paddingTop: 20,
  },
  footerText: {
    color: colors.textSubtle,
    fontSize: 12,
  },
  footerSub: {
    color: colors.cardBorderLight,
    fontSize: 11,
    marginTop: 4,
  },
  errorCard: {
    backgroundColor: colors.errorBg,
    borderWidth: 1,
    borderColor: colors.errorBorder,
    padding: 14,
    borderRadius: 12,
    marginBottom: 20,
  },
  errorText: {
    color: colors.errorText,
    fontSize: 14,
    textAlign: 'center',
  },
});
